import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import localFonts from "next/font/local";
import { notFound } from "next/navigation";

import { routing } from "@/i18n/routing";

import { LocaleHtml } from "./components/LocaleHtml";

const cloudLoop = localFonts({
  src: "./font/CloudLoop-Regular.otf",
  variable: "--font-cloud-loop",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <div className={`${cloudLoop.variable} antialiased`}>
      <LocaleHtml locale={locale} />
      <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
    </div>
  );
}
